HList -r result/migi_itte0.mfc > MFCC_DATA/migi_itte0.txt
HList -r result/chigau_yo2.mfc > MFCC_DATA/chigau_yo2.txt
HList -r result/migi_itte1.mfc > MFCC_DATA/migi_itte1.txt
HList -r result/migi_itte3.mfc > MFCC_DATA/migi_itte3.txt
HList -r result/chigau_yo1.mfc > MFCC_DATA/chigau_yo1.txt
HList -r result/chigau_yo0.mfc > MFCC_DATA/chigau_yo0.txt
HList -r result/chigau_chigau4.mfc > MFCC_DATA/chigau_chigau4.txt
HList -r result/chigau_chigau0.mfc > MFCC_DATA/chigau_chigau0.txt
HList -r result/chigau_chigau1.mfc > MFCC_DATA/chigau_chigau1.txt
HList -r result/migi_itte5.mfc > MFCC_DATA/migi_itte5.txt
HList -r result/chigau_chigau3.mfc > MFCC_DATA/chigau_chigau3.txt
HList -r result/chigau_chigau2.mfc > MFCC_DATA/chigau_chigau2.txt
HList -r result/migi_itte4.mfc > MFCC_DATA/migi_itte4.txt
HList -r result/shita_itte1.mfc > MFCC_DATA/shita_itte1.txt
HList -r result/hidari_itte1.mfc > MFCC_DATA/hidari_itte1.txt
HList -r result/hidari_itte0.mfc > MFCC_DATA/hidari_itte0.txt
HList -r result/shita_itte0.mfc > MFCC_DATA/shita_itte0.txt
HList -r result/shita_itte2.mfc > MFCC_DATA/shita_itte2.txt
HList -r result/hidari_itte2.mfc > MFCC_DATA/hidari_itte2.txt
HList -r result/shita_itte3.mfc > MFCC_DATA/shita_itte3.txt
HList -r result/sou_sou2.mfc > MFCC_DATA/sou_sou2.txt
HList -r result/sou_sou0.mfc > MFCC_DATA/sou_sou0.txt
HList -r result/sou_sou1.mfc > MFCC_DATA/sou_sou1.txt
HList -r result/ue_itte1.mfc > MFCC_DATA/ue_itte1.txt
HList -r result/ue_itte0.mfc > MFCC_DATA/ue_itte0.txt
HList -r result/ue_itte2.mfc > MFCC_DATA/ue_itte2.txt
HList -r result/gyaku_dayo3.mfc > MFCC_DATA/gyaku_dayo3.txt
HList -r result/gyaku_dayo2.mfc > MFCC_DATA/gyaku_dayo2.txt
HList -r result/gyaku_dayo0.mfc > MFCC_DATA/gyaku_dayo0.txt
HList -r result/gyaku_dayo1.mfc > MFCC_DATA/gyaku_dayo1.txt
